name: Conditional env variable

on: workflow_dispatch

jobs:
  configure_ndk:
    runs-on: ubuntu-24.04
    env:
      NDK_VERSION: 28.2.13676358
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # See 'Supported distributions' for available options

      - name: Install android sdk
        uses: malinskiy/action-android/install-sdk@release/0.1.4
        
      - name: Configure android ndk
        run: |
          NDK_PATH=$ANDROID_SDK_ROOT/ndk/$NDK_VERSION
          if [ -d "$NDK_PATH" ]; then
            echo "ANDROID_NDK_HOME=$NDK_PATH" >> $GITHUB_ENV
            echo "Using ndk $NDK_PATH"
          else
            echo "NDK_PATH not found, abort."
            exit 1
          fi    
      - name: Check android ndk
        run: echo "Ndk version is $ANDROID_NDK_HOME"
