name: Conditional env variable

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-24.04
    env:
      Greeting: Hello
      ANDROID_NDK_HOME: ${{ ANDROID_NDK_LATEST_HOME }}
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: 
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK ndk:$ANDROID_NDK_HOME latest ndk:$ANDROID_NDK_LATEST_HOME"
        env:
          First_Name: Mona
